/*
 * Librairy actions types
 */

export const REQUEST_ALBUMS = 'REQUEST_ALBUMS'
export const REQUEST_ALBUMS_SUCCESS = 'REQUEST_ALBUMS_SUCCESS'
export const REQUEST_ALBUMS_FAILURE = 'REQUEST_ALBUMS_FAILURE'

export const REQUEST_PICTURES = 'REQUEST_PICTURES'
export const REQUEST_PICTURES_SUCCESS = 'REQUEST_PICTURES_SUCCESS'
export const REQUEST_PICTURES_FAILURE = 'REQUEST_PICTURES_FAILURE'

export const REQUEST_TAGS = 'REQUEST_TAGS'
export const REQUEST_TAGS_SUCCESS = 'REQUEST_TAGS_SUCCESS'
export const REQUEST_TAGS_FAILURE = 'REQUEST_TAGS_FAILURE'

export const ADD_PICTURE = 'ADD_PICTURE'
export const UPDATE_PICTURE = 'UPDATE_PICTURE'
export const DELETE_PICTURE = 'DELETE_PICTURE'
 
export const ADD_ALBUM = 'ADD_ALBUM'
export const UPDATE_ALBUM = 'UPDATE_ALBUM'
export const DELETE_ALBUM = 'DELETE_ALBUM'
