/*
 * User actions types
 */

export const LOGOUT = 'LOGOUT'
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS'
export const REQUEST_LOGIN_FAILURE = 'REQUEST_LOGIN_FAILURE'
export const REQUEST_REFRESH = 'REQUEST_REFRESH'
export const REQUEST_REFRESH_SUCCESS = 'REQUEST_REFRESH_SUCCESS'
export const REQUEST_REFRESH_FAILURE = 'REQUEST_REFRESH_FAILURE'
export const REQUEST_CURRENT_USER = 'REQUEST_CURRENT_USER'
export const REQUEST_CURRENT_USER_SUCCESS = 'REQUEST_CURRENT_USER_SUCCESS'
export const REQUEST_CURRENT_USER_FAILURE = 'REQUEST_CURRENT_USER_FAILURE'
