/*
 * Pinpict actions types
 */

export const REQUEST_USER = 'REQUEST_USER'
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS'
export const REQUEST_USER_FAILURE = 'REQUEST_USER_FAILURE'

export const REQUEST_USER_PUBLIC_BOARDS = 'REQUEST_USER_PUBLIC_BOARDS'
export const REQUEST_USER_PUBLIC_BOARDS_SUCCESS = 'REQUEST_USER_PUBLIC_BOARDS_SUCCESS'
export const REQUEST_USER_PUBLIC_BOARDS_FAILURE = 'REQUEST_USER_PUBLIC_BOARDS_FAILURE'

export const REQUEST_USER_PRIVATE_BOARDS = 'REQUEST_USER_PRIVATE_BOARDS'
export const REQUEST_USER_PRIVATE_BOARDS_SUCCESS = 'REQUEST_USER_PRIVATE_BOARDS_SUCCESS'
export const REQUEST_USER_PRIVATE_BOARDS_FAILURE = 'REQUEST_USER_PRIVATE_BOARDS_FAILURE'

export const STORE_BOARD_ABSTRACT = 'STORE_BOARD_ABSTRACT'

export const REQUEST_PIN = 'REQUEST_PIN'
export const REQUEST_PIN_SUCCESS = 'REQUEST_PIN_SUCCESS'
export const REQUEST_PIN_FAILURE = 'REQUEST_PIN_FAILURE'

export const REQUEST_TAGS = 'REQUEST_TAGS'
export const REQUEST_TAGS_SUCCESS = 'REQUEST_TAGS_SUCCESS'
export const REQUEST_TAGS_FAILURE = 'REQUEST_TAGS_FAILURE'

export const REQUEST_SCAN = 'REQUEST_SCAN'
export const REQUEST_SCAN_SUCCESS = 'REQUEST_SCAN_SUCCESS'
export const REQUEST_SCAN_FAILURE = 'REQUEST_SCAN_FAILURE'

export const REQUEST_SHORT_BOARD = 'REQUEST_SHORT_BOARD'
export const REQUEST_SHORT_BOARD_SUCCESS = 'REQUEST_SHORT_BOARD_SUCCESS'
export const REQUEST_SHORT_BOARD_FAILURE = 'REQUEST_SHORT_BOARD_FAILURE'

export const REQUEST_FULL_BOARD = 'REQUEST_FULL_BOARD'
export const REQUEST_FULL_BOARD_SUCCESS = 'REQUEST_FULL_BOARD_SUCCESS'
export const REQUEST_FULL_BOARD_FAILURE = 'REQUEST_FULL_BOARD_FAILURE'

export const SELECT_USER = 'SELECT_USER'
export const SELECT_BOARD = 'SELECT_BOARD'
export const SELECT_PIN = 'SELECT_PIN'
